<div class="panel panel-default">
	<div class="panel-heading">Produto</div>
	<?php echo $this->form()->openTag($form)?>
		<div class="panel-body">
			<div class="form-group">
				<label for="codigo"><?php echo $this->formLabel($form->get('codigo'))?></label>
				<?php echo $this->formElement($form->get('codigo'))?>
				<?php echo $this->formElementErrors($form->get('codigo'))?>
			</div>

			<div class="form-group">
				<label for="categoria"><?php echo $this->formLabel($form->get('categoria'))?></label>
				<?php echo $this->formElement($form->get('categoria'))?>
				<?php echo $this->formElementErrors($form->get('categoria'))?>
			</div>

			<div class="form-group">
				<label for="ativo"><?php echo $this->formLabel($form->get('ativo'))?></label>
				<?php echo $this->formElement($form->get('ativo'))?>
				<?php echo $this->formElementErrors($form->get('ativo'))?>
			</div>

			<div class="form-group">
				<label for="nome"><?php echo $this->formLabel($form->get('nome'))?></label>
				<?php echo $this->formElement($form->get('nome'))?>
				<?php echo $this->formElementErrors($form->get('nome'))?>
			</div>

			<div class="form-group">
				<label for="slug"><?php echo $this->formLabel($form->get('slug'))?></label>
				<?php echo $this->formElement($form->get('slug'))?>
				<?php echo $this->formElementErrors($form->get('slug'))?>
			</div>

			<div class="form-group">
				<label for="descricao"><?php echo $this->formLabel($form->get('descricao'))?></label>
				<?php echo $this->formElement($form->get('descricao'))?>
				<?php echo $this->formElementErrors($form->get('descricao'))?>
			</div>

			<div class="form-group">
				<label for="peso"><?php echo $this->formLabel($form->get('peso'))?></label>
				<?php echo $this->formElement($form->get('peso'))?>
				<?php echo $this->formElementErrors($form->get('peso'))?>
			</div>


			<?php if (count($atributosTipo)):?>
			<div class="form-group">
				<?php foreach ($atributosTipo as $atributoTipo):?>
				<div class="panel panel-primary" style="width: 700px">
			  		<div class="panel-heading">Atributo <?php echo $atributoTipo->getNome()?></div>
					<?php if (count($atributoTipo->getAtributos())):?>
					<div class="panel-body">
						<?php foreach ($atributoTipo->getAtributos() as $atributo):?>
				    	<label for="atributo_<?php echo $atributo->getId()?>">
							<input type="checkbox" id="atributo_<?php echo $atributo->getId()?>" name="atributo[<?php echo $atributo->getId()?>]" value="<?php echo $atributo->getId()?>" <?php if (in_array($atributo->getId(), $arrAtributos)):?>checked="checked"<?php endif;?> /> <?php echo $atributo->getNome()?>
						</label>
						<?php endforeach;?>
		  			</div>
					<?php endif;?>
				</div>
				<?php endforeach;?>
			</div>
			<?php endif;?>

			<div class="form-group">
				<div class="panel panel-primary" style="width: 700px">
			  		<div class="panel-heading">Características</div>
					<div class="panel-body">
						<div>
							<select id="caracteristicaPerfil" name="caracteristicaPerfil">
								<option></option>
								<?php if (count($caracteristicaPerfil)):
									foreach ($caracteristicaPerfil as $item):?>
										<option value="<?php echo $item->getId()?>"><?php echo $item->getNome()?></option>
								<?php
									endforeach;
								endif?>
							</select>
						</div>
						<ul id="caracteristicas">
							<?php
							if (isset($caracteristicas) && count($caracteristicas)):
								foreach ($caracteristicas as $caracteristica):?>
								<li>
							    	<label for="atributo_<?php echo $caracteristica->getCaracteristica()->getId()?>">
										<input type="checkbox" id="caracterisca_check_<?php echo $caracteristica->getCaracteristica()->getId()?>" name="caracteristica_check[<?php echo $caracteristica->getCaracteristica()->getId()?>]" value="<?php echo $caracteristica->getCaracteristica()->getId()?>" <?php if (in_array($caracteristica->getCaracteristica()->getId(), $viewCaracteristicas)):?>checked="checked"<?php endif;?> /> <?php echo $caracteristica->getCaracteristica()->getNome()?>
										<input type="text" id="caracterisca_valor_<?php echo $caracteristica->getCaracteristica()->getId()?>" name="caracteristica_valor[<?php echo $caracteristica->getCaracteristica()->getId()?>]" value="<?php echo $caracteristica->getValor()?>" />
									</label>
								</li>
							<?php
								endforeach;
							endif;
							?>
						</ul>
		  			</div>
				</div>
			</div>

		</div>
		<div class="panel-footer">
			<input type="button" onclick="document.location.href='/admin/<?php echo $controller?>'" value="Voltar">
			<input type="submit" value="Salvar">
		</div>
	<?php echo $this->form()->closeTag($form)?>
</div>
<!-- Scripts -->
<?php echo $this->headScript()->appendFile($this->basePath() . '/js/produto/editar.js'); ?>