<div class="panel panel-default">
	<div class="panel-heading">
		<a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'cadastrar'))?>" class="btn btn-primary">Novo produto</a>
	</div>

	<div class="panel-body">
		<form action="" name="form" method="get">
			<table class="table">
				<thead>
					<tr>
						<td>ID</td>
						<td>Ativo</td>
						<td>Categoria</td>
						<td>Nome</td>
						<td>Preço</td>
						<td>Data inc</td>
						<td>Estoque</td>
						<td>Opções</td>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><input type="text" name="id" value="<?php echo isset($filtro['id']) ? $filtro['id'] : ""?>"></td>
						<td>
							<select name="ativo">
								<option value="">--</option>
								<option value="1" <?php echo $filtro['ativo'] == 1 ? "selected" : ""?>>Ativo</option>
								<option value="0" <?php echo $filtro['ativo'] == "0" ? "selected" : ""?>>Inativo</option>
							</select>
						</td>
						<td>
							<select name="perfil">
								<option value="">--</option>
								<?php foreach ($categorias as $categoria):?>
								<option value="<?php echo $categoria->getId()?>" <?php echo $filtro['categoria'] == $categoria->getId() ? "selected" : ""?>><?php echo $categoria->getNome()?></option>
									<?php
									if (count($categoria->getChildren())):
										foreach ($categoria->getChildren() as $categoriaFilha):?>
									<option value="<?php echo $categoriaFilha->getId()?>" <?php echo $filtro['categoria'] == $categoriaFilha->getId() ? "selected" : ""?>> -> <?php echo $categoriaFilha->getNome()?></option>
									<?php
										endforeach;
									endif;?>
								<?php endforeach;?>
							</select>
						</td>
						<td><input type="text" name="nome" value="<?php echo isset($filtro['nome']) ? $filtro['nome'] : ""?>"></td>
						<td><input type="text" name="preco" value="<?php echo isset($filtro['preco']) ? $filtro['preco'] : ""?>"></td>
						<td><input type="text" name="data_inc" value="<?php echo isset($filtro['data_inc']) ? $filtro['data_inc'] : ""?>"></td>
						<td></td>
						<td><input type="submit" value="Filtrar"></td>
					</tr>
					<?php
					if (count($data)):
						foreach ($data as $item):
						$preco = $this->preco($item->getId());
					?>
					<tr>
						<td><?php echo $item->getId()?></td>
						<td><?php echo $item->getAtivo()?></td>
						<td>
						<?php
							if ($item->getCategoria()->getCategoria()):
								echo $item->getCategoria()->getCategoria()->getNome() . " -> ";
							endif;
							echo $item->getCategoria()->getNome()
						?>
						</td>
						<td><?php echo $item->getNome()?></td>
						<td>
							<?php if (count($preco)):?>
								<?php if (isset($preco['precoNovo'])):?>
									<div style="font-size: 10px;">R$ <?php echo $preco['precoAtual']?></div>
									<div>R$ <?php echo $preco['precoNovo']?></div>
								<?php else:?>
									<div>R$ <?php echo $preco['precoAtual']?></div>
								<?php endif?>
							<?php else:?>
								não existe um preço válido.
							<?php endif?>
						</td>
						<td><?php echo $item->getDtaInc()->format('d/m/Y H:i')?></td>
						<td><a href="<?php echo $this->url('admin/default', array('controller' => 'estoque', 'action' => 'index', 'id' => $item->getId()))?>" class="btn btn-primary"><?php echo $this->estoque($item->getId())?></a></td>
						<td>
							<a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'foto', 'id' => $item->getId()))?>"><i class="glyphicon glyphicon-camera"></a></i>
							<a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'editar', 'id' => $item->getId()))?>"><i class="glyphicon glyphicon-pencil"></a></i>
							<a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'delete', 'id' => $item->getId()))?>" onclick="return confirm('Tem certeza que deseja excluir este registro?')"><i class="glyphicon glyphicon-remove"></a></i>
						</td>
					</tr>
					<?php
						endforeach;
					endif;?>
				</tbody>
			</table>
		</form>
	</div>
	<div class="panel-footer" style="text-align: center;">
		<?php echo $this->paginationControl($data, 'Sliding', 'partials/paginator.phtml')?>
	</div>
</div>