<div class="panel panel-default">
	<div class="panel-heading">
		<a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'cadastrar'))?>" class="btn btn-primary">Novo frete</a>
	</div>
	
	<div class="panel-body">
		<form action="" name="form" method="get">
			<table class="table">
				<thead>
					<tr>
						<td>ID</td>
						<td>Transporte</td>
						<td>Faixa cep de</td>
						<td>Faixa cep até</td>
						<td>Valor</td>
						<td>Opções</td>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><input type="text" name="id" value="<?php echo isset($filtro['id']) ? $filtro['id'] : ""?>"></td>
						<td>
							<select name="categoria">
								<option value="">--</option>
								<?php foreach ($transportes as $idTransporte => $nomeTransporte):?>
								<option value="<?php echo $idTransporte?>" <?php echo $filtro['transporte'] == $idTransporte ? "selected" : ""?>><?php echo $nomeTransporte?></option>
								<?php endforeach;?>
							</select>
						</td>
						<td><input type="text" name="faixa_cep_de" value="<?php echo isset($filtro['faixa_cep_de']) ? $filtro['faixa_cep_de'] : ""?>"></td>
						<td><input type="text" name="faixa_cep_para" value="<?php echo isset($filtro['faixa_cep_para']) ? $filtro['faixa_cep_para'] : ""?>"></td>
						<td><input type="text" name="vlr" value="<?php echo isset($filtro['vlr']) ? $filtro['vlr'] : ""?>"></td>
						<td><input type="submit" value="Filtrar"></td>
					</tr>
					<?php 
					if (count($data)):
						foreach ($data as $item):?>
					<tr>
						<td><?php echo $item->getId()?></td>
						<td><?php echo $item->getTransporte() ? $item->getTransporte()->getNome() : ""?></td>
						<td><?php echo $item->getFaixaCepDe()?></td>
						<td><?php echo $item->getFaixaCepAte()?></td>
						<td><?php echo $item->getVlr()?></td>
						<td>
							<a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'editar', 'id' => $item->getId()))?>"><i class="glyphicon glyphicon-pencil"></a></i>
							<a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'delete', 'id' => $item->getId()))?>" onclick="return confirm('Tem certeza que deseja excluir este registro?')"><i class="glyphicon glyphicon-remove"></a></i>
						</td>
					</tr>
					<?php 
						endforeach;
					endif;?>
				</tbody>
			</table>
		</form>
	</div>
	<div class="panel-footer" style="text-align: center;">
		<?php echo $this->paginationControl($data, 'Sliding', 'partials/paginator.phtml')?>
	</div>
</div>