<div class="panel panel-default">
	<div class="panel-heading">
		<a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'cadastrar'))?>" class="btn btn-primary">Nova categoria</a>
	</div>
	
	<div class="panel-body">
		<form action="" name="form" method="get">
			<table class="table">
				<thead>
					<tr>
						<td>ID</td>
						<td>Categoria</td>
						<td>Nome</td>
						<td>Status</td>
						<td>Opções</td>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><input type="text" name="id" value="<?php echo isset($filtro['id']) ? $filtro['id'] : ""?>"></td>
						<td>
							<select name="categoria">
								<option value="">--</option>
								<?php foreach ($categorias as $categoria):?>
								<option value="<?php echo $categoria->getId()?>" <?php echo $filtro['categoria'] == $categoria->getId() ? "selected" : ""?>><?php echo $categoria->getNome()?></option>
								<?php endforeach;?>
							</select>
						</td>
						<td><input type="text" name="nome" value="<?php echo isset($filtro['nome']) ? $filtro['nome'] : ""?>"></td>
						<td>
							<select name="status">
								<option value="">--</option>
								<option value="1" <?php echo $filtro['status'] == 1 ? "selected" : ""?>>Ativo</option>
								<option value="0" <?php echo $filtro['status'] == "0" ? "selected" : ""?>>Inativo</option>
							</select>
						</td>
						<td><input type="submit" value="Filtrar"></td>
					</tr>
					<?php 
					if (count($data)):
						foreach ($data as $item):?>
					<tr>
						<td><?php echo $item->getId()?></td>
						<td><?php echo $item->getCategoria() ? $item->getCategoria()->getNome() : ""?></td>
						<td><?php echo $item->getNome()?></td>
						<td><?php echo $item->getStatus()?></td>
						<td>
							<a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'editar', 'id' => $item->getId()))?>"><i class="glyphicon glyphicon-pencil"></a></i>
							<a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'delete', 'id' => $item->getId()))?>" onclick="return confirm('Tem certeza que deseja excluir este registro?')"><i class="glyphicon glyphicon-remove"></a></i>
						</td>
					</tr>
					<?php 
						endforeach;
					endif;?>
				</tbody>
			</table>
		</form>
	</div>
	<div class="panel-footer" style="text-align: center;">
		<?php echo $this->paginationControl($data, 'Sliding', 'partials/paginator.phtml')?>
	</div>
</div>