<?php
$urlPattern = $_SERVER['REQUEST_URI'];
$formatUrl = function ($page) use ($urlPattern) {
    if (!preg_match('/page/', $urlPattern))
        return $urlPattern . "/page/" . $page;
    else
        return preg_replace('/\d/', $page, $urlPattern);
};
?>
<div>
    <?php if ($this->pageCount): ?>
        <ul class="pagination">
            <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?> de <?php echo $this->totalItemCount; ?> páginas
            <br />


            <!-- First page link -->
            <?php if (isset($this->previous)): ?>

                <li>
                    <a href="<?php echo $formatUrl($this->previous) ?>">
                        <<
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <<
                    </a>
                </li>
            <?php endif; ?>


            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $formatUrl($page); ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>


            <!-- Last page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $formatUrl($this->next); ?>">
                        >>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        >>
                    </a>
                </li>
            <?php endif; ?>

        </ul>

    <?php endif; ?>
</div>