<div class="panel panel-default">
	<div class="panel-heading">Estoque</div>
	<?php echo $this->form()->openTag($form)?>
		<div class="panel-body">
			
			<div class="form-group">
				<label for="tipo"><?php echo $this->formLabel($form->get('tipo'))?></label>
				<?php echo $this->formElement($form->get('tipo'))?>
				<?php echo $this->formElementErrors($form->get('tipo'))?>
			</div>
			
			<div class="form-group">
				<label for="qtd"><?php echo $this->formLabel($form->get('qtd'))?></label>
				<?php echo $this->formElement($form->get('qtd'))?>
				<?php echo $this->formElementErrors($form->get('qtd'))?>
			</div>
		
		</div>
		<div class="panel-footer">
			<input type="button" onclick="document.location.href='/admin/<?php echo $controller?>'" value="Voltar">
			<input type="submit" value="Salvar">			
		</div>
	<?php echo $this->form()->closeTag($form)?>
</div>