								<div class="category-toolbar clearfix">
									<div class="toolbox-filter clearfix">

										<div class="sort-box">
											<span class="separator">sort by:</span>
											<div class="btn-group select-dropdown">
												<button type="button" class="btn select-btn">Position</button>
												<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
													<i class="fa fa-angle-down"></i>
												</button>
												<ul class="dropdown-menu" role="menu">
													<li><a href="#">Date</a></li>
													<li><a href="#">Name</a></li>
												</ul>
											</div>
										</div>

										<div class="view-box">
											<a href="category.html" class="active icon-button icon-grid"><i class="fa fa-th-large"></i></a>
											<a href="category-list.html" class="icon-button icon-list"><i class="fa fa-th-list"></i></a>
										</div><!-- End .view-box -->

									</div><!-- End .toolbox-filter -->
									<div class="toolbox-pagination clearfix">
										<ul class="pagination">
											<li class="active"><a href="#">1</a></li>
											<li><a href="#">2</a></li>
											<li><a href="#">3</a></li>
											<li><a href="#">4</a></li>
											<li><a href="#">5</a></li>
											<li><a href="#"><i class="fa fa-angle-right"></i></a></li>
										</ul>
										<div class="view-count-box">
											<span class="separator">view:</span>
											<div class="btn-group select-dropdown">
												<button type="button" class="btn select-btn">10</button>
												<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
													<i class="fa fa-angle-down"></i>
												</button>
												<ul class="dropdown-menu" role="menu">
													<li><a href="#">15</a></li>
													<li><a href="#">30</a></li>
												</ul>
											</div>
										</div><!-- End .view-count-box -->

									</div><!-- End .toolbox-pagination -->


        						</div><!-- End .category-toolbar -->
        						<div class="md-margin"></div><!-- .space -->
        						<div class="category-item-container">
        						<div class="row">
        							<?php
        							if (count($produtos)):
        								foreach ($produtos as $produto):
        								$preco = $this->preco($produto->getId());
        							?>
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									<div class="item-image-container">
											<figure>
												<a href="<?php echo $this->url('produto_detalhe', array('slug' => $produto->getSlug()))?>">
													<img src="<?php echo $this->basePath . '/arquivos/produtos/thumbs/' . $produto->getId() . '/' . $produto->getFoto()[0]->getArquivo()?>" alt="<?php echo $produto->getFoto()[0]->getArquivo()?>" class="item-image">
													<img src="<?php echo $this->basePath . '/arquivos/produtos/thumbs/' . $produto->getId() . '/' . $produto->getFoto()[0]->getArquivo()?>" alt="<?php echo $produto->getFoto()[0]->getArquivo()?>  Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
	        										<?php if (count($preco)):?>
														<?php if (isset($preco['precoNovo'])):
															$desconto = ((($preco['precoNovo'] * 100) / $preco['precoAtual']) - 100);
														?>
															<span class="old-price">R$ <?php echo $preco['precoAtual']?></span>
															<span class="item-price">R$ <?php echo $preco['precoNovo']?></span>
														<?php else:?>
															<span class="item-price">R$ <?php echo $preco['precoAtual']?></span>
														<?php endif?>
													<?php endif?>
												</div>
												<?php if (isset($desconto)):?>
													<span class="discount-rect"><?php echo round($desconto)?>%</span>
												<?php endif;?>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<h3 class="item-name"><a href="<?php echo $this->url('produto_detalhe', array('slug' => $produto->getSlug()))?>"><?php echo $produto->getNome()?></a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->
        								</div><!-- End .item -->

        							</div><!-- End .col-md-4 -->
        							<?php
        								endforeach;
        							endif;?>

        						</div><!-- End .row -->
        						</div><!-- End .category-item-container -->

        						<div class="pagination-container clearfix">
        							<div class="pull-right">
										<ul class="pagination">
											<li class="active"><a href="#">1</a></li>
											<li><a href="#">2</a></li>
											<li><a href="#">3</a></li>
											<li><a href="#">4</a></li>
											<li><a href="#">5</a></li>
											<li><a href="#"><i class="fa fa-angle-right"></i></a></li>
											</ul>
        							</div><!-- End .pull-right -->

        							<div class="pull-right view-count-box hidden-xs">
										<span class="separator">view:</span>
										<div class="btn-group select-dropdown">
											<button type="button" class="btn select-btn">10</button>
											<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
												<i class="fa fa-angle-down"></i>
											</button>
											<ul class="dropdown-menu" role="menu">
												<li><a href="#">15</a></li>
												<li><a href="#">30</a></li>
											</ul>
										</div>
									</div>
        						</div><!-- End pagination-container -->