					<div class="col-md-12">
						<header class="content-title">
							<h1 class="title">Login or Create An Account</h1>
                            <div class="md-margin"></div><!-- space -->
						</header>
        			
						   <div class="row">
							   	
							   	<div class="col-md-6 col-sm-6 col-xs-12">					   		
							   		<h2>New Customer</h2>
							   		
							   	<p>By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.</p>
                                <div class="md-margin"></div><!-- space -->
							   	<a href="register-account.html" class="btn btn-custom-2">Create An Account</a>
                                <div class="lg-margin"></div><!-- space -->
							   	</div><!-- End .col-md-6 -->
							   	<div class="col-md-6 col-sm-6 col-xs-12">					   		
							   		<h2>Registered Customers</h2>
							   		<p>If you have an account with us, please log in.</p>
							   		<div class="xs-margin"></div>
							   		
									<form id="login-form" method="post" action="<?php echo $this->url('user/default', array('controller' => 'login'))?>">
                                        <div class="input-group">
                                            <span class="input-group-addon"><span class="input-icon input-icon-email"></span><span class="input-text">Email&#42;</span></span>
                                            <?php echo $this->formElement($form->get('email'))?>
                                            <?php echo $this->formElementErrors($form->get('email'))?>
                                        </div><!-- End .input-group -->
                                         <div class="input-group xs-margin">
                                            <span class="input-group-addon"><span class="input-icon input-icon-password"></span><span class="input-text">Senha&#42;</span></span>
                                            <?php echo $this->formElement($form->get('senha'))?>
                                            <?php echo $this->formElementErrors($form->get('senha'))?>
                                        </div><!-- End .input-group -->
                                    <span class="help-block text-right"><a href="<?php echo $this->url('user/default', array('controller' => 'forgot'))?>">Esqueceu a senha?</a></span>
                                    <button class="btn btn-custom-2">LOGIN</button>
                                    </form>
                                    <div class="sm-margin"></div><!-- space -->
							   	</div><!-- End .col-md-6 -->
							   	
						   </div><!-- End.row -->
								   
        			</div><!-- End .col-md-12 -->