<div class="panel panel-default">
	<div class="panel-heading">Atributo</div>
	<?php echo $this->form()->openTag($form)?>
		<div class="panel-body">

			<div class="form-group">
				<label for="nome"><?php echo $this->formLabel($form->get('nome'))?></label>
				<?php echo $this->formElement($form->get('nome'))?>
				<?php echo $this->formElementErrors($form->get('nome'))?>
			</div>

			<div class="form-group">
				<label for="codigo"><?php echo $this->formLabel($form->get('codigo'))?></label>
				<?php echo $this->formElement($form->get('codigo'))?>
				<?php echo $this->formElementErrors($form->get('codigo'))?>
			</div>

			<div class="form-group">
				<label for="atributo_tipo"><?php echo $this->formLabel($form->get('atributo_tipo'))?></label>
				<?php echo $this->formElement($form->get('atributo_tipo'))?>
				<?php echo $this->formElementErrors($form->get('atributo_tipo'))?>
			</div>

		</div>
		<div class="panel-footer">
			<input type="button" onclick="document.location.href='/admin/<?php echo $controller?>'" value="Voltar">
			<input type="submit" value="Salvar">
		</div>
	<?php echo $this->form()->closeTag($form)?>
</div>