<div class="panel panel-default">
	<div class="panel-body">
		<form action="" name="form" method="get">
			<table class="table">
				<thead>
					<tr>
						<td>ID pedido</td>
						<td>Clietne</td>
						<td>Status</td>
						<td>Data inclusão</td>
						<td>Valor total pedido</td>
						<td>Opções</td>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><input type="text" name="id" value="<?php echo isset($filtro['id']) ? $filtro['id'] : ""?>"></td>
						<td><input type="text" name="usuario" value="<?php echo isset($filtro['usuario']) ? $filtro['usuario'] : ""?>"></td>
						<td><input type="text" name="nome" value="<?php echo isset($filtro['nome']) ? $filtro['nome'] : ""?>"></td>
						<td>
							<select name="pedido_status">
								<option value="">--</option>
								<?php foreach ($listaPedidoStatus as $id => $nome):?>
								<option value="<?php echo $id?>" <?php echo $filtro['pedido_status'] == $id ? "selected" : ""?>><?php echo $nome?></option>
								<?php endforeach;?>
							</select>
						</td>
						<td></td>
						<td></td>
						<td><input type="submit" value="Filtrar"></td>
					</tr>
					<?php 
					if (count($data)):
						foreach ($data as $item):?>
					<tr>
						<td><?php echo $item->getId()?></td>
						<td><?php echo $item->getUsuario()->getNome()?></td>
						<td><?php echo $item->getPedidoStatus()->getNome()?></td>
						<td><?php echo $item->getDtaInc()->format('d/m/Y H:i')?></td>
						<td><?php echo $item->getVlrTotal()?></td>
						<td>
							<a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'editar', 'id' => $item->getId()))?>"><i class="glyphicon glyphicon-pencil"></a></i>
							<a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'delete', 'id' => $item->getId()))?>" onclick="return confirm('Tem certeza que deseja excluir este registro?')"><i class="glyphicon glyphicon-remove"></a></i>
						</td>
					</tr>
					<?php 
						endforeach;
					endif;?>
				</tbody>
			</table>
		</form>
	</div>
	<div class="panel-footer" style="text-align: center;">
		<?php echo $this->paginationControl($data, 'Sliding', 'partials/paginator.phtml')?>
	</div>
</div>