<div class="panel panel-default">
	<div class="panel-heading">Resource</div>
	<?php echo $this->form()->openTag($form)?>
		<div class="panel-body">
			
			<div class="form-group">
				<label for="nome"><?php echo $this->formLabel($form->get('nome'))?></label>
				<?php echo $this->formElement($form->get('nome'))?>
				<?php echo $this->formElementErrors($form->get('nome'))?>
			</div>

			<div class="form-group">
				<label for="codigo"><?php echo $this->formLabel($form->get('codigo'))?></label>
				<?php echo $this->formElement($form->get('codigo'))?>
				<?php echo $this->formElementErrors($form->get('codigo'))?>
			</div>

            <div class="form-group">
                <label for="descricao"><?php echo $this->formLabel($form->get('descricao'))?></label>
                <?php echo $this->formElement($form->get('descricao'))?>
                <?php echo $this->formElementErrors($form->get('descricao'))?>
            </div>

            <div class="form-group">
                <label for="tipo"><?php echo $this->formLabel($form->get('tipo'))?></label>
                <?php echo $this->formElement($form->get('tipo'))?>
                <?php echo $this->formElementErrors($form->get('tipo'))?>
            </div>

            <div class="form-group">
                <label for="tipo_desconto"><?php echo $this->formLabel($form->get('tipo_desconto'))?></label>
                <?php echo $this->formElement($form->get('tipo_desconto'))?>
                <?php echo $this->formElementErrors($form->get('tipo_desconto'))?>
            </div>

            <div class="form-group">
                <label for="dta_ini"><?php echo $this->formLabel($form->get('dta_ini'))?></label>
                <?php echo $this->formElement($form->get('dta_ini'))?>
                <?php echo $this->formElementErrors($form->get('dta_ini'))?>
            </div>

            <div class="form-group">
                <label for="dta_fim"><?php echo $this->formLabel($form->get('dta_fim'))?></label>
                <?php echo $this->formElement($form->get('dta_fim'))?>
                <?php echo $this->formElementErrors($form->get('dta_fim'))?>
            </div>

            <div class="form-group">
                <label for="valor"><?php echo $this->formLabel($form->get('valor'))?></label>
                <?php echo $this->formElement($form->get('valor'))?>
                <?php echo $this->formElementErrors($form->get('valor'))?>
            </div>

        </div>
		<div class="panel-footer">
			<input type="button" onclick="document.location.href='/admin/<?php echo $controller?>'" value="Voltar">
			<input type="submit" value="Salvar">			
		</div>
	<?php echo $this->form()->closeTag($form)?>
</div>