<div class="panel panel-default">
	<div class="panel-heading">
		<a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'cadastrar'))?>" class="btn btn-primary">Novo resource</a>
	</div>
	
	<div class="panel-body">
		<form action="" name="form" method="get">
			<table class="table">
				<thead>
					<tr>
						<td style="width: 50px;">ID</td>
						<td>Nome</td>
						<td>Código</td>
						<td>Data inc</td>
						<td>Validade</td>
						<td>Tipo</td>
						<td>Tipo Desconto</td>
						<td>Valor</td>
						<td style="width: 70px;">Opções</td>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><input style="width: 40px;" type="text" name="id" value="<?php echo isset($filtro['id']) ? $filtro['id'] : ""?>"></td>
						<td><input type="text" name="nome" value="<?php echo isset($filtro['nome']) ? $filtro['nome'] : ""?>"></td>
						<td><input style="width: 60px" type="text" name="codigo" value="<?php echo isset($filtro['codigo']) ? $filtro['codigo'] : ""?>"></td>
						<td></td>
						<td></td>
						<td>
                            <select name="tipo">
                                <option></option>
                                <option value="1" <?php echo (isset($filtro['tipo']) && $filtro['tipo'] == 1) ? "selected" : ""?>>Desconto Item</option>
                                <option value="2" <?php echo (isset($filtro['tipo']) && $filtro['tipo'] == 2) ? "selected" : ""?>>Desconto Carrinho</option>
                            </select>
						<td>
                            <select name="tipo_desconto">
                                <option></option>
                                <option value="1" <?php echo (isset($filtro['tipo_desconto']) && $filtro['tipo_desconto'] == 1) ? "selected" : ""?>>Valor</option>
                                <option value="2" <?php echo (isset($filtro['tipo_desconto']) && $filtro['tipo_desconto'] == 2) ? "selected" : ""?>>Porcentagem</option>
                            </select>
						<td><input style="width: 60px" type="text" name="valor" value="<?php echo isset($filtro['valor']) ? $filtro['valor'] : ""?>"></td>
						<td><input type="submit" value="Filtrar"></td>
					</tr>
					<?php 
					if (count($data)):
						foreach ($data as $item):?>
					<tr>
						<td><?php echo $item->getId()?></td>
						<td><?php echo $item->getNome()?></td>
						<td><?php echo $item->getCodigo()?></td>
						<td><?php echo $item->getDtaInc()->format("d/m/Y H:i")?></td>
						<td>-<?php echo $item->getDtaIni()->format("d/m/Y H:i")?> -<?php echo $item->getDtaFim()->format("d/m/Y H:i")?></td>
						<td>
                            <?php
                            if ($item->getTipo() == 1):
                                echo 'Desconto no item';
                            else:
                                echo 'Desconto no pedido';
                            endif;
                            ?>
                        </td>
                        <td>
                            <?php
                            if ($item->getTipoDesconto() == 1):
                                echo 'Desconto em valores';
                            else:
                                echo 'Desconto em porcentagem';
                            endif;
                            ?>
                        </td>
                        <td><?php echo $this->currencyFormat($item->getValor(), 'BRL', 'pt_BR')?></td>
						<td>
							<a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'editar', 'id' => $item->getId()))?>"><i class="glyphicon glyphicon-pencil"></a></i>
							<a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'delete', 'id' => $item->getId()))?>" onclick="return confirm('Tem certeza que deseja excluir este registro?')"><i class="glyphicon glyphicon-remove"></a></i>
						</td>
					</tr>
					<?php 
						endforeach;
					endif;?>
				</tbody>
			</table>
		</form>
	</div>
	<div class="panel-footer" style="text-align: center;">
		<?php echo $this->paginationControl($data, 'Sliding', 'partials/paginator.phtml')?>
	</div>
</div>