        						<header class="content-title">
									<h2 class="title">Our Products</h2>
									<p class="title-desc">Save your money and time with our store. Here's the best part of our impressive assortment.</p>
								</header>
        						<ul id="products-tabs-list" class="tab-style-1 clearfix">
        							<li class="active"><a href="#all" data-toggle="tab">All</a></li>
        							<li><a href="#latest" data-toggle="tab">Latest</a></li>
        							<li><a href="#featured" data-toggle="tab">Featured</a></li>
        							<li><a href="#bestsellers" data-toggle="tab">Bestsellers</a></li>
        							<li><a href="#special" data-toggle="tab">Special</a></li>
        						</ul>
        						
        						<div id="products-tabs-content" class="row tab-content">
        							<div class="tab-pane active" id="all">
									<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
												<div class="item-image-container">
													<figure>
													<a href="product.html">
														<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 1" class="item-image">
														<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 1 Hover" class="item-image-hover">
													</a>
													</figure>
													<div class="item-price-container">
														<span class="old-price">$160</span>
														<span class="item-price">$120</span>
													</div>
													<span class="new-rect">New</span>
													<span class="discount-rect">-30%</span>
												</div><!-- End .item-image -->
											
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="90"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 2" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 2 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$199</span>
												</div>
												<span class="discount-rect">-30%</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="80"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 3" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 3 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$99<span class="sub-price">.75</span></span>
												</div>
												<span class="new-rect">New</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Headphones 1" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Headphones 1 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$79<span class="sub-price">.99</span></span>
												</div>
												<span class="new-rect">New</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 4" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 4 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$120</span>
												</div>
												<span class="discount-rect">-20%</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="60"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        								
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 5" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 5 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
        											<span class="old-price">$110<span class="sub-price">.99</span></span>
													<span class="item-price">$95<span class="sub-price">.99</span></span>
												</div>
												<span class="new-rect">New</span>
												<span class="discount-rect">-15%</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="40"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							</div><!-- End .tab-pane -->
        							
        							<div class="tab-pane" id="latest">
        								<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="item1" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="item1  Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
        											<span class="old-price">$210<span class="sub-price">.99</span></span>
													<span class="item-price">$180<span class="sub-price">.99</span></span>
												</div>
												<span class="new-rect">New</span>
												<span class="discount-rect">-15%</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="70"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        							</div><!-- End .col-md-4 -->
        							
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="item2" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="item2 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$110<span class="sub-price">.991</span></span>
												</div>
												<span class="new-rect">New</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        							</div><!-- End .col-md-4 -->
        							
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="item3" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="item3 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
        											<span class="old-price">$100</span>
													<span class="item-price">$75</span>
												</div>
												<span class="new-rect">New</span>
												<span class="discount-rect">-25%</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="90"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        							</div><!-- End .col-md-4 -->
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 2" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 2 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$199</span>
												</div>
												<span class="discount-rect">-30%</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="80"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 3" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 3 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$99<span class="sub-price">.75</span></span>
												</div>
												<span class="new-rect">New</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Headphones 1" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Headphones 1 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$79<span class="sub-price">.99</span></span>
												</div>
												<span class="new-rect">New</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							</div><!-- End .tab-pane -->
        							
        							<div class="tab-pane" id="featured">
									<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="item3" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="item3 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$160<span class="sub-price">.99</span></span>
												</div>
												<span class="new-rect">New</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="95"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												1 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        							</div><!-- End .col-md-4 -->
        							
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 1" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 1 Hover" class="item-image-hover">
												</a>
											</figure>
												<div class="item-price-container">
													<span class="old-price">$160</span>
													<span class="item-price">$120</span>
												</div>
												<span class="new-rect">New</span>
												<span class="discount-rect">-20%</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="90"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 2" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 2 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$199</span>
												</div>
												<span class="discount-rect">-30%</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="80"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 2" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 2 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$199</span>
												</div>
												<span class="discount-rect">-30%</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="80"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 3" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 3 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$99<span class="sub-price">.75</span></span>
												</div>
												<span class="new-rect">New</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Headphones 1" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Headphones 1 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$79<span class="sub-price">.99</span></span>
												</div>
												<span class="new-rect">New</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							</div><!-- End .tab-pane -->
        							<div class="tab-pane" id="bestsellers">
        								<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="item1" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="item1  Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
        											<span class="old-price">$210<span class="sub-price">.99</span></span>
													<span class="item-price">$16<span class="sub-price">.99</span></span>
												</div>
												<span class="new-rect">New</span>
												<span class="discount-rect">-15%</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="70"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        							</div><!-- End .col-md-4 -->
        							
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="item2" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="item2 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$110<span class="sub-price">.991</span></span>
												</div>
												<span class="new-rect">New</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        							</div><!-- End .col-md-4 -->
        							
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="item3" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="item3 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
        											<span class="old-price">$100</span>
													<span class="item-price">$75</span>
												</div>
												<span class="new-rect">New</span>
												<span class="discount-rect">-25%</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="90"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        							</div><!-- End .col-md-4 -->
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 2" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 2 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$199</span>
												</div>
												<span class="discount-rect">-30%</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="80"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 3" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 3 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$99<span class="sub-price">.75</span></span>
												</div>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Headphones 1" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Headphones 1 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$79<span class="sub-price">.99</span></span>
												</div>
												<span class="new-rect">New</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							</div><!-- End .tab-pane -->
        							<div class="tab-pane" id="special">
        								<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="item3" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="item3 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$160<span class="sub-price">.99</span></span>
												</div>
												<span class="new-rect">New</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="95"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												1 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        							</div><!-- End .col-md-4 -->
        							
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 1" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 1 Hover" class="item-image-hover">
												</a>
											</figure>
												<div class="item-price-container">
													<span class="old-price">$160</span>
													<span class="item-price">$120</span>
												</div>
												<span class="new-rect">New</span>
												<span class="discount-rect">-20%</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="90"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 2" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 2 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$199</span>
												</div>
												<span class="discount-rect">-30%</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="80"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 2" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 2 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$199</span>
												</div>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="80"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 3" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 3 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$99<span class="sub-price">.75</span></span>
												</div>
												<span class="new-rect">New</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							
        							<div class="col-md-4 col-sm-6 col-xs-12">
        								<div class="item">
        									
        									<div class="item-image-container">
											<figure>	
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Headphones 1" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Headphones 1 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$79<span class="sub-price">.99</span></span>
												</div>
												<span class="new-rect">New</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->
        								
        								
        							</div><!-- End .col-md-4 -->
        							</div><!-- End .tab-pane -->
        						</div><!-- End #products-tabs-content -->
        						
        						<div class="sm-margin"></div><!-- Space -->
								<div class="row">
									<div class="col-md-7 col-sm-7 col-xs-12">
                                        <header class="content-title">
                                            <h2 class="title">Welcome to Venedor</h2>
                                        </header>
										<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Venedor is a fully responsive Magento theme with advanced admin module. Based on Bootstrap’s 12 column 1200px responsive grid Theme. Great looks on desktops, tablets and mobiles. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Venedor is extremely customizable, easy to use and fully responsive. Suitable for every type of store. Great as a starting point for your custom projects. This theme includes several extensions including ajax price slider that will help you improve your sales. We supply a full help with our products and after purchase support to all our customers. <a href="#">Buy Venedor Theme!</a></p>
									</div><!-- End .col-md-7 -->
									<div class="col-md-5 col-sm-5 col-xs-12">
                                        <div class="sm-margin visible-xs"></div><!-- space -->
										<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/showcase.png" alt="Showcase Venedor" class="img-responsive">
									</div><!-- End .col-md-5 -->
								</div><!-- End .row -->
        						<div class="xlg-margin"></div><!-- Space -->
        						
        						<div class="hot-items carousel-wrapper">
        							<header class="content-title">
										<div class="title-bg">
											<h2 class="title">On Sale</h2>
										</div><!-- End .title-bg -->
										<p class="title-desc">Only with us you can get a new model with a discount.</p>
									</header>

                                <div class="carousel-controls">
                                    <div id="hot-items-slider-prev" class="carousel-btn carousel-btn-prev">
                                    </div><!-- End .carousel-prev -->
                                    <div id="hot-items-slider-next" class="carousel-btn carousel-btn-next carousel-space">
                                    </div><!-- End .carousel-next -->
                                </div><!-- End .carousel-controls -->
        						<div class="hot-items-slider owl-carousel">
        									<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="item3" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="item3 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$160<span class="sub-price">.99</span></span>
												</div>
												<span class="new-rect">New</span>
												<span class="discount-rect">-10%</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="95"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												1 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->

        									<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Phone 3" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Phone 3 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$99<span class="sub-price">.75</span></span>
												</div>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        									</div><!-- End .item -->
        									<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="Headphones 1" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="Headphones 1 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$79<span class="sub-price">.99</span></span>
												</div>
												<span class="new-rect">New</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->

        									<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="item3" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="item3 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
        											<span class="old-price">$100</span>
													<span class="item-price">$75</span>
												</div>
												<span class="new-rect">New</span>
												<span class="discount-rect">-25%</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="90"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												3 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->

        									<div class="item">
        									
        									<div class="item-image-container">
											<figure>
												<a href="product.html">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder.jpg" alt="item3" class="item-image">
													<img src="<?php echo $this->basePath() . '/skin/frontend/'?>/images/products/placeholder-hover.jpg" alt="item3 Hover" class="item-image-hover">
												</a>
											</figure>
        										<div class="item-price-container">
													<span class="item-price">$180<span class="sub-price">.99</span></span>
												</div>
												<span class="new-rect">New</span>
        									</div><!-- End .item-image -->
        									<div class="item-meta-container">
        										<div class="ratings-container">
        											<div class="ratings">
        												<div class="ratings-result" data-result="95"></div>
        											</div><!-- End .ratings -->
        											<span class="ratings-amount">
        												2 Reviews
        											</span>
        										</div><!-- End .rating-container -->
        										<h3 class="item-name"><a href="product.html">Lorem Ipsum Dolla</a></h3>
        										<div class="item-action">
        											<a href="#" class="item-add-btn">
														<span class="icon-cart-text">Add to Cart</span>
													</a>
        											<div class="item-action-inner">
        												<a href="#" class="icon-button icon-like">Favourite</a>
        												<a href="#" class="icon-button icon-compare">Checkout</a>
        											</div><!-- End .item-action-inner -->
        										</div><!-- End .item-action -->
        									</div><!-- End .item-meta-container -->	
        								</div><!-- End .item -->

        						</div><!--hot-items-slider -->
        						<div class="lg-margin"></div><!-- Space -->
        						</div><!-- End .hot-items -->