<div class="panel panel-default">
	<div class="panel-heading">Transporte</div>
	<?php echo $this->form()->openTag($form)?>
		<div class="panel-body">
			
			<div class="form-group">
				<label for="nome"><?php echo $this->formLabel($form->get('nome'))?></label>
				<?php echo $this->formElement($form->get('nome'))?>
				<?php echo $this->formElementErrors($form->get('nome'))?>
			</div>
			
			<div class="form-group">
				<label for="status"><?php echo $this->formLabel($form->get('status'))?></label>
				<?php echo $this->formElement($form->get('status'))?>
				<?php echo $this->formElementErrors($form->get('status'))?>
			</div>
		
		</div>
		<div class="panel-footer">
			<input type="button" onclick="document.location.href='/admin/<?php echo $controller?>'" value="Voltar">
			<input type="submit" value="Salvar">			
		</div>
	<?php echo $this->form()->closeTag($form)?>
</div>