<section id="content">
    <div id="breadcrumb-container">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="index.html">Home</a></li>
                <li class="active">Shopping Cart</li>
            </ul>
        </div>
    </div>
    <div class="container">
    <div class="row">
        <div class="col-md-12">
            <?php if (count($itens)): ?>
        <header class="content-title">
            <h1 class="title">Shopping Cart</h1>
            <p class="title-desc">Just this week, you can use the free premium delivery.</p>
        </header>
        <div class="xs-margin"></div><!-- space -->
        <div class="row">

            <div class="col-md-12 table-responsive">

                <table class="table cart-table">
                    <thead>
                        <tr>
                            <th class="table-title">Produto None</th>
                            <th class="table-title">Código</th>
                            <th class="table-title">Preço Unit.</th>
                            <th class="table-title">Quantidade</th>
                            <th class="table-title">SubTotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $total = 0;
                        $totalGeral = 0;
                        foreach ($itens as $produto):
                            $total += $produto->getPrice() * $produto->getQuantity();
                            ?>
                        <tr>
                            <td class="item-name-col">
                                <figure>
                                    <a href="#"><img src="<?php echo $this->basePath() ?>/arquivos/produtos/<?php echo $produto->getId() ?>/<?php echo $produto->getImage() ?>" alt="Lowlands Lace Blouse"></a>
                                </figure>
                                <header class="item-name"><a href="#"><?php echo $produto->getDescription() ?></a></header>
                                <?php if(count($produto->getAttributes())): ?>
                                <ul>
                                    <?php
                                    foreach ($produto->getAttributes() as $key => $value):
                                        if ($value > 0):
                                    ?>
                                    <li><?php echo ucfirst($key)?>: <?php echo $this->atributo($value)?></li>
                                    <?php
                                        endif;
                                    endforeach;
                                    ?>
                                </ul>
                                <?php endif?>
                            </td>
                            <td class="item-code"><?php echo $produto->getProductCode()?></td>
                            <td class="item-price-col"><span class="item-price-special"><?php echo $this->currencyFormat($produto->getPrice(), 'BRL', 'pt_BR') ?></span></td>
                            <td>
                                <?php echo $produto->getQuantity() ?>
                            </td>
                            <td class="item-total-col"><span class="item-price-special"><?php echo $this->currencyFormat(($produto->getPrice() * $produto->getQuantity()), 'BRL', 'pt_BR') ?></span>
                                <a href="<?php echo $this->url('carrinho_item_remove', array('id' => $produto->getId())) ?>" class="close-button" onclick="return confirm('Você tem certeza que deseja excluir este produto?')"></a>
                            </td>
                        </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>

            </div><!-- End .col-md-12 -->

        </div><!-- End .row -->
        <div class="lg-margin"></div><!-- End .space -->

        <div class="row">
            <div class="col-md-8 col-sm-12 col-xs-12">

                <div class="tab-container left clearfix">
                    <ul class="nav-tabs">
                        <li class="active"><a href="#shipping" data-toggle="tab">Calculo de frete</a></li>
                        <li><a href="#discount" data-toggle="tab">Discount Code</a></li>
                        <li><a href="#gift" data-toggle="tab">Gift voucher </a></li>

                    </ul>
                    <div class="tab-content clearfix">
                        <div class="tab-pane active" id="shipping">

                            <div class="row">
                                <form id="form-calculo-frete" action="<?php echo $this->url('carrinho_adicionar_frete')?>" method="post">
                                    <div class="col-md-12 col-sm-12 col-xs-12">
                                        <div class="input-group">
                                            <span class="input-group-addon"><span class="input-icon input-icon-user"></span><span class="input-text">CEP: *</span></span>
                                            <input type="text" name="cep" id="cep" required class="form-control input-lg" placeholder="Digite o seu cep">
                                        </div><!-- End .input-group -->

                                    </div>
                                    <input type="button" id="calcular-frete" class="btn btn-custom-2 md-margin" value="Calcular">
                                </form>
                            </div>

                        </div><!-- End .tab-pane -->

                        <div class="tab-pane" id="discount">
                            <p>Enter your discount coupon code here.</p>
                            <form action="<?php echo $this->url('carrinho_aplicar_cupom') ?>" method="post">
                                <div class="input-group">
                                    <input type="text" name="cupom" required class="form-control" placeholder="Coupon code" value="<?php echo $discountCode ?>">

                                </div><!-- End .input-group -->
                                <input type="submit" class="btn btn-custom-2" value="Aplicar CUPOM">
                            </form>
                        </div><!-- End .tab-pane -->

                        <div class="tab-pane" id="gift">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi dignissimos nostrum debitis optio molestiae in quam dicta labore obcaecati ullam necessitatibus animi deleniti minima dolor suscipit nobis est excepturi inventore.</p>
                        </div><!-- End .tab-pane -->

                    </div><!-- End .tab-content -->
                </div><!-- End .tab-container -->

            </div><!-- End .col-md-8 -->
            <div class="lg-margin visible-sm visible-xs"></div><!-- space -->
            <div class="col-md-4 col-sm-12 col-xs-12">

                <table class="table total-table">
                    <tbody>
                        <tr>
                            <td class="total-table-title">Subtotal:</td>
                            <td><?php echo $this->currencyFormat($total, 'BRL', 'pt_BR');?></td>
                        </tr>
                        <tr>
                            <td class="total-table-title">Frete:</td>
                            <td><?php
                                $valorFrete = count($frete) ? $frete['valor'] : 0;
                                $totalGeral = $total + $valorFrete;
                                if ($cupom > 0) {
                                    $totalGeral = ($totalGeral - $cupom);
                                }
                                echo $this->currencyFormat($valorFrete, 'BRL', 'pt_BR');
                                ?></td>
                        </tr>
                        <tr>
                            <td class="total-table-title">Desconto:</td>
                            <td>
                                <?php if ($cupom > 0): ?>
                                    <?php echo $this->currencyFormat($cupom, 'BRL', 'pt_BR'); ?>
                                <?php endif ?></td>
                        </tr>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td>Total:</td>
                        <td><?php echo $this->currencyFormat($totalGeral, 'BRL', 'pt_BR'); ?></td>
                    </tr>
                    </tfoot>
                </table>
                <div class="md-margin"></div><!-- End .space -->
                <a href="<?php echo $this->url('produtos')?>" class="btn btn-custom-2">CONTINUE COMPRANDO</a>
                <a href="#" class="btn btn-custom">CHECKOUT</a>
            </div><!-- End .col-md-4 -->
        </div><!-- End .row -->
        <div class="lg-margin2x"></div><!-- Space -->


        <?php else:?>
                Carrinho vazio!

        <?php endif?>
        </div><!-- End .col-md-12 -->
    </div><!-- End .row -->
    </div><!-- End .container -->
</section>
<script type="text/javascript" src="/js/carrinho/listar.js"></script>