					<div class="col-md-12">
						<header class="content-title">
							<h1 class="title">Register Account</h1>
							<p class="title-desc">If you already have an account, please login at <a href="#">login page</a>.</p>
						</header>
        				<div class="xs-margin"></div><!-- space -->
						<form action="<?php echo $this->url('user/default', array('controller' => 'cadastrar')) ?>" id="register-form" method="post" name="register-form">
        				<div class="row">
        					
								<div class="col-md-6 col-sm-6 col-xs-12">
									
									<fieldset>
									<h2 class="sub-title">Detalhes pessoais</h2>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-icon input-icon-user"></span><span class="input-text">Nome &#42;</span></span>
										<?php echo $this->formElement($formUsuario->get('usuario_nome'))?>
										<?php echo $this->formElementErrors($formUsuario->get('usuario_nome'))?>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-icon input-icon-email"></span><span class="input-text">Email &#42;</span></span>
										<?php echo $this->formElement($formUsuario->get('email'))?>
										<?php echo $this->formElementErrors($formUsuario->get('email'))?>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-icon input-icon-password"></span><span class="input-text">RG &#42;</span></span>
										<?php echo $this->formElement($formDadosPessoais->get('rg'))?>
										<?php echo $this->formElementErrors($formDadosPessoais->get('rg'))?>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-icon input-icon-password"></span><span class="input-text">CPF &#42;</span></span>
										<?php echo $this->formElement($formDadosPessoais->get('cpf'))?>
										<?php echo $this->formElementErrors($formDadosPessoais->get('cpf'))?>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-icon input-icon-phone"></span><span class="input-text">Telefone &#42;</span></span>
										<?php echo $this->formElement($formDadosPessoais->get('telefone'))?>
										<?php echo $this->formElementErrors($formDadosPessoais->get('telefone'))?>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-icon input-icon-phone"></span><span class="input-text">Celular &#42;</span></span>
										<?php echo $this->formElement($formDadosPessoais->get('celular'))?>
										<?php echo $this->formElementErrors($formDadosPessoais->get('celular'))?>
									</div>
									
									</fieldset>
									
									<fieldset>
									<h2 class="sub-title">Defina uma senha</h2>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-icon input-icon-postcode"></span><span class="input-text">Senha&#42;</span></span>
										<?php echo $this->formElement($formUsuario->get('senha'))?>
										<?php echo $this->formElementErrors($formUsuario->get('senha'))?>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-icon input-icon-postcode"></span><span class="input-text">Confirme a Senha&#42;</span></span>
										<?php echo $this->formElement($formUsuario->get('confirme_senha'))?>
										<?php echo $this->formElementErrors($formUsuario->get('confirme_senha'))?>
									</div>
									</fieldset>
									
									
								</div><!-- End .col-md-6 -->
        						
        						<div class="col-md-6 col-sm-6 col-xs-12">
        						<fieldset>
									<h2 class="sub-title">Endereço</h2>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-icon input-icon-address"></span><span class="input-text">Endereço&#42;</span></span>
										<?php echo $this->formElement($formEndereco->get('logradouro'))?>
										<?php echo $this->formElementErrors($formEndereco->get('logradouro'))?>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-icon input-icon-user"></span><span class="input-text">Número&#42;</span></span>
										<?php echo $this->formElement($formEndereco->get('numero'))?>
										<?php echo $this->formElementErrors($formEndereco->get('numero'))?>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-icon input-icon-user"></span><span class="input-text">Complemento&#42;</span></span>
										<?php echo $this->formElement($formEndereco->get('complemento'))?>
										<?php echo $this->formElementErrors($formEndereco->get('complemento'))?>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-icon input-icon-user"></span><span class="input-text">Bairro&#42;</span></span>
										<?php echo $this->formElement($formEndereco->get('bairro'))?>
										<?php echo $this->formElementErrors($formEndereco->get('bairro'))?>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-icon input-icon-city"></span><span class="input-text">Cidade&#42;</span></span>
										<?php echo $this->formElement($formEndereco->get('cidade'))?>
										<?php echo $this->formElementErrors($formEndereco->get('cidade'))?>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-icon input-icon-region"></span><span class="input-text">Estado&#42;</span></span>
										<?php echo $this->formElement($formEndereco->get('estado'))?>
										<?php echo $this->formElementErrors($formEndereco->get('estado'))?>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><span class="input-icon input-icon-postcode"></span><span class="input-text">CEP&#42;</span></span>
										<?php echo $this->formElement($formEndereco->get('cep'))?>
										<?php echo $this->formElementErrors($formEndereco->get('cep'))?>
									</div>
									
									</fieldset>
        						</div><!-- End .col-md-6 -->
        					
        				</div><!-- End .row -->
						
						<div class="row">
							<div class="col-md-6 col-sm-6 col-xs-12">
								<input type="submit" value="Criar conta" class="btn btn-custom-2 btn-lg md-margin">
							</div><!-- End .col-md-6 -->
						</div><!-- End .row -->
        				</form>
        			</div><!-- End .col-md-12 -->
        		</div><!-- End .row -->